volumes:
  postgresql-data:

services:
  postgres:
    container_name: postgres.bookkeeping
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}

    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DATABASE}
      interval: 5s
      retries: 5

    volumes:
      - postgresql-data:/var/lib/postgresql/

    restart: unless-stopped

  migrations:
    depends_on:
      postgres:
        condition: service_healthy

    container_name: migrate.bookkeeping

    build:
      dockerfile: Dockerfile
      context: .
    command: "poetry run alembic upgrade head"

    volumes:
      - ./conf/alembic.ini:/app/alembic.ini

    restart: "no"

  main-service:
    depends_on:
      migrations:
        condition: service_completed_successfully
    container_name: bookkeeping

    build:
      dockerfile: Dockerfile
      context: .

    volumes:
      - ./conf/settings.yaml:/app/settings.yaml
      - ./conf/secrets.yaml:/app/.secrets.yaml

    ports:
      - "8000:8000"

    restart: unless-stopped